---
name: Checks

on: [push]

jobs:
  test-lint:  # This is the name of the job
    name: Test and Lint  # This is the name of the job that will be displayed in the GitHub Actions UI
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2  # This is the action that we are using to log in to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3  # This is the action that we are using to check out the code
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"  # This is the command that we are running to test the code
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"  # This is the command that we are running to lint the code